project:
  type: website
website:
  title: "My Quarto Website"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
    right:
      - icon: github
         href: https://github.com/phorni-2293
         
        - about.qmd
  
format:
  html:
    theme: 
      light: flatly
      dark: darkly

editor: visual

